### ISSUE TITLE
Filenames with æøå won't play

### ISSUE THREAD

**Issue by 7u5a** [tv2/casparcg-cliptool#57]
Filenames with danish letters like æøå won't play.
The ClipTool can see them, but won't play.

**Comment by olzzon** [comment]
I've looked into this. And it looks like CasparCG 2.3.x returns filename with capital letters, and for some reason it does not translate it back, as it does with the letters A-Z
Same behavior is seen in CasparCG Client (2.0.8 and 2.2.0)

So Capital ÆØÅ works but not lower case æøå, but it looks like a limit in CCG
