### ISSUE TITLE
Timecode disapeared

### ISSUE THREAD

**Issue by 7u5a** [tv2/casparcg-cliptool#58]
When loading the ClipTool, everything was fine.
Playing clips, and have countdown.
Suddenly did'nt have countdown.
Don't know if it was caused by the CasparCG client, trying to play some audio and gfx on the same channel?
It was not enough to restart CasparCG client, ClipTool or the Server and Mediascanner.

**Comment by olzzon** [comment]
I'll let this be open. 
Have tried messing around but can't seem to reproduce the bug, please report back if you find a way to reproduce it 💯 
Normally countdown is lost when the OSC connection from CCG to ClipTool is lost.

**Comment by MediaCenterRUV** [comment]
The Timecode and preview is also not appearing for me.
I have the <osc> segment in the config.
I'm running the tool from the localhost.

**Comment by olzzon** [comment]
@MediaCenterRUV your problem sounds more like the OSC protocol is not activated.
Could you post your casparcg.config file

**Comment by MediaCenterRUV** [comment]
<?xml version="1.0" encoding="utf-8"?>

<configuration>
    <paths>
      <media-path>D:\media\</media-path>
      <log-path>log/</log-path>
      <data-path>data/</data-path>
      <template-path>D:\templates\</template-path>
    </paths>
    <lock-clear-phrase>secret</lock-clear-phrase>
    <html>
      <enable-gpu>false</enable-gpu>
    </html>
    <channels>
      <channel>
        <video-mode>1080i5000</video-mode>
	<consumers>
          <decklink>
            <device>1</device>
            <embedded-audio>true</embedded-audio>
            <keyer>external</keyer>
            <key-only>false</key-only>
            <buffer-depth>3</buffer-depth>
          </decklink>
        </consumers>
      </channel>
      <channel>
        <video-mode>1080i5000</video-mode>
	<consumers>
          <decklink>
            <device>2</device>
            <embedded-audio>true</embedded-audio>
            <keyer>external</keyer>
            <key-only>false</key-only>
            <buffer-depth>3</buffer-depth>
          </decklink>
        </consumers>
      </channel>
      <channel>
        <video-mode>1080i5000</video-mode>
	<consumers>
          <decklink>
            <device>3</device>
            <embedded-audio>true</embedded-audio>
            <keyer>external</keyer>
            <key-only>false</key-only>
            <buffer-depth>3</buffer-depth>
          </decklink>
        </consumers>
      </channel>
      <channel>
        <video-mode>1080i5000</video-mode>
	<consumers>
          <decklink>
            <device>4</device>
            <embedded-audio>true</embedded-audio>
            <keyer>external</keyer>
            <key-only>false</key-only>
            <buffer-depth>3</buffer-depth>
          </decklink>
        </consumers>
      </channel>
    </channels>
    <controllers>
        <tcp>
            <port>5250</port>
            <protocol>AMCP</protocol>
        </tcp>
    </controllers>
    <amcp>
        <media-server>
            <host>localhost</host>
            <port>8000</port>
        </media-server>
    </amcp>
</configuration>

**Comment by MediaCenterRUV** [comment]
[casparcg.conf.txt](https://github.com/olzzon/CasparCG-ClipTool/files/7251155/casparcg.conf.txt)

**Comment by olzzon** [comment]
This should be moved up to a part of the configuration. Right now it's placed in the comments.

```
<osc>
  <default-port>6250</default-port>
  <disable-send-to-amcp-clients>false [true|false]</disable-send-to-amcp-clients>
  <predefined-clients>
    <predefined-client>
      <address>127.0.0.1</address>
      <port>5253</port>
    </predefined-client>
  </predefined-clients>
</osc>
```

**Comment by MediaCenterRUV** [comment]
inside the configuration section then?

**Comment by MediaCenterRUV** [comment]
Thank you...now it works! :)

Very nice. Will probably be used in our main studio to feed loops in set monitors.

**Comment by olzzon** [comment]
Thanks 👍 
I'll close this issue and have updated the README.md file for clearer explanation of this.
