### ISSUE TITLE
Timecode jumps

### ISSUE THREAD

**Issue by 7u5a** [tv2/casparcg-cliptool#66]
I have some clips, when I load them, the timecode starts at 00:01:33:26.
When I play them, the timecode starts running.
Suddenly the timecode just 00:00:30:26
The actual file is about 33 seconds.

**Comment by olzzon** [comment]
@KvelaGorrrrnio has actually fixed this in latest develop branch. But it's not in v.2.10.1
Could you try out the version in develop branch:
[package/casparcg-clip-tool.exe](https://github.com/tv2/casparcg-cliptool/blob/cea792e704b5d837639784467b11ddaec3c20b56/package/casparcg-clip-tool.exe)

@KvelaGorrrrnio i think we should see if we could make a release flow in Actions

**Comment by olzzon** [comment]
@7u5a did the latest develop branch fix the problem?
If not, what videoformat are you using, resolution AND framerate

**Comment by KvelaGorrrrnio** [comment]
> @KvelaGorrrrnio has actually fixed this in latest develop branch. But it's not in v.2.10.1 Could you try out the version in develop branch: [package/casparcg-clip-tool.exe](https://github.com/tv2/casparcg-cliptool/blob/cea792e704b5d837639784467b11ddaec3c20b56/package/casparcg-clip-tool.exe)
> 
> @KvelaGorrrrnio i think we should see if we could make a release flow in Actions

@olzzon Let us have a look at that.

**Comment by 7u5a** [comment]
@olzzon it seems to work now.
Tried some different clips.

**Comment by olzzon** [comment]
@7u5a great to hear :) 
I'll close this one for now them
